### ISSUE TITLE
Win32 audio player feature request

### ISSUE THREAD

**Issue by SaadArdati** [halildurmus/win32#100]
Hi, I was wondering how simple it would be to implement the audio api from win32
https://docs.microsoft.com/en-us/windows/win32/coreaudio/about-the-windows-core-audio-apis
It's quite large, but enables fully-featured audio and music players on windows

**Comment by timsneath** [comment]
It's doable, but it's quite a low-level API compared to Media Foundation or others. Is there a reason you'd want to stay so close to the metal?

**Comment by SaadArdati** [comment]
@timsneath No real reason other than that this is what I was suggested to use. I have no experience with windows apis and was told to use this, and that this package can interface with win32. If you have more knowledge on a simpler solution, I'd ecstatic

**Comment by timsneath** [comment]
The modern API for media playback is [MediaPlayer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/play-audio-and-video-with-mediaplayer), which is supported in Windows 10 v1607 or later. Would this work for you? I'd be interested in trying to wrap this for you. 

[Media Foundation](https://docs.microsoft.com/en-us/windows/win32/medfound/about-the-media-foundation-sdk) is the legacy API from Windows Vista days, built on top of the low-level Core Audio APIs you linked to above. It's the most broadly compatible API, but is probably going to be painful to call from Dart or Flutter code, because it's very much designed around C++ calling conventions. I wouldn't recommend this, I don't think.

**Comment by SaadArdati** [comment]
Flutter for windows supports versions below win10, doesn't it? If that is the case, then perhaps do win32 APIs but add an abstraction layer in dart that greatly simplifies usage. If it doesn't support below win10, then definitely go with MediaPlayer.

If worst comes to worst, perhaps do MediaPlayer and MediaFoundation, run the one most appropriate for the windows version + an abstraction layer for common functionality between both.

What do you think?

**Comment by timsneath** [comment]
I think that is a scope of work beyond this project: to not only provide interop to two very large and complex APIs but also design and implement a clean abstraction on top of both. That's probably a great package in its own right. 

It's possible to build apps for older versions than Windows 10 with Flutter, but Microsoft themselves don't support Windows 7 any longer (it's 11 years old, after all!)

**Comment by SaadArdati** [comment]
Honestly, then I'd go for the MediaPlayer api for win10 then :) you have a great point

**Comment by timsneath** [comment]
Adding @slightfoot for interest [based on his comment](https://twitter.com/devangelslondon/status/1308478729765740545).

**Comment by slightfoot** [comment]
I'll update this issue with a link to a PR that contains my code when I have time to finish it off.

**Comment by Teajayy007** [comment]
does this Win32 API include the WASAPI for mic audio recording? I would like to make and audio recording stream app for flutter windows. @timsneath

**Comment by insinfo** [comment]
I'm also interested in the Windows core audio API as it allows for low latency audio to for example build an audio editor application with realtime recording and processing
