### ISSUE TITLE
`IPhoneNumberFormatterStatics` fails to generate the correct output for `phoneNumber`

### ISSUE THREAD

**Issue by timsneath** [halildurmus/win32#224]
https://docs.microsoft.com/en-us/uwp/api/windows.globalization.phonenumberformatting.phonenumberformatter.trycreate?view=winrt-19041

```dart
typedef _TryCreate_Native = Int32 Function(
    Pointer obj, IntPtr regionCode, ____ phoneNumber);
typedef _TryCreate_Dart = int Function(
    Pointer obj, int regionCode, ____ phoneNumber);
```

This is a `PhoneNumberFormatter` and I think it should therefore be `Pointer<Uint32>`.

**Comment by timsneath** [comment]
Probably fixed in the new generation code; need to try this afresh.

**Comment by halildurmus** [comment]
> Probably fixed in the new generation code; need to try this afresh.

I tried to generate it but it didn't work. Then I tried to print `methodParams` variable inside the `WinRTMethodProjection` and got this exception: `Type information missing for ReferenceTypeModifier.` 

It seems that `ReferenceTypeModifier`'s `TypeTuple` is not specified in `tool/projection/type.dart`. 
I fixed it like this but I'm not sure whether this will work for every `ReferenceTypeModifier`:
```diff
...

+   bool get isReferenceType =>
+      typeIdentifier.baseType == BaseType.ReferenceTypeModifier;

...
    if (isInterface ||
+       isReferenceType ||
        typeIdentifier.baseType == BaseType.ClassTypeModifier ||
        typeIdentifier.baseType == BaseType.Object) {
      return const TypeTuple('Pointer<COMObject>', 'Pointer<COMObject>');
    }

    // default: return the name as returned by metadata
    throw Exception('Type information missing for $typeIdentifier.');
  }
}
```

Then I found a bug caused by my latest PR (#405) while trying to use the `TryCreate` function.

`TryCreate` function is generated as :
```dart
  void TryCreate(
    int regionCode,
    Pointer<COMObject> phoneNumber,
  ) =>
      ptr.ref.lpVtbl.value
          .elementAt(6)
          .cast<
              Pointer<
                  NativeFunction<
                      HRESULT Function(
            Pointer,
            IntPtr regionCode,
            Pointer<COMObject> phoneNumber,
          )>>>()
          .value
          .asFunction<
              int Function(
            Pointer,
            int regionCode,
            Pointer<COMObject> phoneNumber,
          )>()(
        ptr.ref.lpVtbl,
        regionCode,
        phoneNumber.cast<Pointer<COMObject>>().value,
      );
```

When I tried to call the function, it crashed. By changing the line with `phoneNumber.cast<Pointer<COMObject>>().value,` to `phoneNumber`, it worked. 

So it looks like we shouldn't be dereferencing parameters whose `BaseType` is `ReferenceTypeModifier`.
