### ISSUE TITLE
Packing string lists

### ISSUE THREAD

**Issue by bsutton** [halildurmus/win32#232]
I've found the library method unpackStringArray in the unpack_utf16.dart library.

Is there a library that does the reverse?

Something like?

```
Pointer<Utf16> packStringArray(List<String> array)
```

I'm trying to update the windows PATH via the registry and it requires a packed string.

**Comment by bsutton** [comment]
So I surprised myself and got this working :)

```dart

/// Packs a List of Dart Strings into a native memory block.
/// Each String is terminated by a null with a 
/// double null to represent the end of the list.
/// The resulting format is that required to write a list of values
/// to the registry.
///
/// It is the responsibility of the caller to [free] the returned
/// pointer.
Pointer<Utf16> packStringArray(List<String> values) {
  var size = 0;

  // calculate the amount of memory we need to store
  // all of the strings.
  for (final value in values) {
    size += value.length + 1;
  }

  /// trailing null after last value
  size++;

  final pArray = calloc<Uint16>(size);
  final ptr = pArray.cast<Uint16>().asTypedList(size);

  var index = 0;
  for (final value in values) {
    final units = value.codeUnits;

    ptr.setAll(index, units);
    ptr[index + units.length] = 0;

    index += value.length + 1;
  }
  ptr[index] = 0;

  return pArray.cast();
}
```

I wasn't certain where to put the code so I've not raised a PR, but if you find the code useful feel free to include it in the win32 project.

thanks for the excellent work !

**Comment by timsneath** [comment]
This is a splendid idea. 

I _think_ this would make sense as an extension on `List<String>` (perhaps called something like `toWideCharArray`?), in the same vein as the `toAnsi()` extension method on `String` for old-school 8-bit APIs:
https://github.com/timsneath/win32/blob/1bf518ba460cfbaf883960fec28857614356872f/lib/src/extensions/set_ansi.dart#L5-L27

One other note: there's a function `wsalloc` here that does string allocation: https://github.com/timsneath/win32/blob/1bf518ba460cfbaf883960fec28857614356872f/lib/src/utils.dart#L82

You might use that when you allocate `pArray` so that its type is obvious and you don't have to cast it again on return. 

Thanks so much for your contribution!
