### ISSUE TITLE
WebView by using win32

### ISSUE THREAD

**Issue by kechankrisna** [halildurmus/win32#272]
If any possible way to embed WebView into flutter widget? If you have any solution, please. This api would be so helpful for a lot of flutter dev.
Here is a ref from ms: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32

**Comment by timsneath** [comment]
There's a prototype implementation by @clarkezone that just draws over Flutter content here, using method channels.
https://github.com/clarkezone/flutter_win_webview

This is not production-ready, not least because the [Windows desktop implementation of Flutter does not yet support platform views](https://github.com/flutter/flutter/issues/31713). 

Leaving this issue open for now, but most of the work to be done is on the Flutter engine side. With that complete, in theory the implementation above could be written using just Dart code.

**Comment by timsneath** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/37597, which is coming when https://github.com/flutter/flutter/issues/31713 is complete.
