### ISSUE TITLE
Implement Kernel API

### ISSUE THREAD

**Issue by victorshx** [halildurmus/win32#284]
Hi Tim,

The bindings for the documented kernel API seems to be missing, specifically [winternl.h](https://docs.microsoft.com/en-us/windows/win32/api/winternl/). I looked through the tool directory and tried to generate the structs and API but to no avail. Being able to call `NtQuerySystemInformation` is a blessing, considering the lack of ability to retrieve more system information right now.

Last and foremost, thanks for this package! It works wonders.

**Comment by timsneath** [comment]
Of course! I'm glad that this package works well for you.

While they're documented, these are internal APIs, as [this note](https://docs.microsoft.com/en-us/windows/win32/devnotes/calling-internal-apis) highlights. Since they aren't guaranteed to be stable across versions of Windows, I'd be leery about including them in this package. 

It is possible to call this using the win32 package though, using the LoadLibrary / GetProcAddress functions described in the above doc. You can find an example of this approach here: 
https://github.com/timsneath/win32/blob/main/example/dynamic_load.dart

**Comment by victorshx** [comment]
> It is possible to call this using the win32 package though, using the LoadLibrary / GetProcAddress functions described in the above doc. You can find an example of this approach here:
> https://github.com/timsneath/win32/blob/main/example/dynamic_load.dart

Oh, how did I miss this example? I'll try this approach, thanks for your work!
