### ISSUE TITLE
File association / default programs

### ISSUE THREAD

**Issue by imranismail** [halildurmus/win32#375]
https://docs.microsoft.com/en-us/windows/win32/shell/default-programs

Hi, thanks for the lib.

I was wondering if you could expose the APIs required to setup file assocs and default programs.

**Comment by timsneath** [comment]
It looks like this is obsolete as of Windows 10. 

If you're only targeting older versions of Windows, you can achieve the approach outlined in this article by writing to the registry. You might find the [win32_registry](https://pub.dev/packages/win32_registry) provides an easier way to go about that, since it provides a high-level abstraction over win32 for registry reading/writing.
