### ISSUE TITLE
WinRT interfaces that contain static methods erroneously import the parent class

### ISSUE THREAD

**Issue by timsneath** [halildurmus/win32#489]
After running `tools\generate.cmd`, it seems as if `iphonenumberinfostatics.dart` and `iphonenumberformatterstatics.dart` now import `phonenumberinfo.dart` and `phonenumberformatter.dart` respectively. 

They seem unnecessary; we should trim them out. I _think_ this might have been introduced by a recent change of yours, @halildurmus -- not sure though :)

**Comment by halildurmus** [comment]
First of all, these imports are correct because `IPhoneNumberFormatterStatics`'s `TryCreate` method has an out parameter that take `PhoneNumberFormatter`, and `IPhoneNumberInfoStatics` has `TryParse` methods that take `PhoneNumberInfo` as a parameter.

Now, these imports only started to be generated after #490 -- which makes sense since reference types were broken before that which prevented these imports from being generated.

**Comment by timsneath** [comment]
Ah, OK -- thank you for clarifying. I don't think I was properly paying attention :(
