### ISSUE TITLE
Possible use after free bug?

### ISSUE THREAD

**Issue by timsneath** [halildurmus/win32#563]
If we're returning this as an `IMapView`, should we be freeing it? Isn't this a "use after free" bug where the memory is still used after it has been freed? @halildurmus 

https://github.com/timsneath/win32/blob/220c807d765518eb7d0216e59c9a13b0bebcfdce/tool/generator/lib/src/projection/winrt/declarations/map.dart#L110

**Comment by halildurmus** [comment]
> If we're returning this as an `IMapView`, should we be freeing it?

We are not returning that as an `IMapView`. We return it as a `Map` by using `toMap()` helper function:
https://github.com/timsneath/win32/blob/220c807d765518eb7d0216e59c9a13b0bebcfdce/tool/generator/lib/src/projection/winrt/declarations/map.dart#L107

In the `toMap` function, we allocate the `pArray` pointer to hold the elements of the `IMapView` ~~and we do not free that pointer so that it's safe to use when we expose them through a `Map`~~: https://github.com/timsneath/win32/blob/220c807d765518eb7d0216e59c9a13b0bebcfdce/lib/src/winrt/internal/map_helpers.dart#L23-L31

**EDIT:** On second thought, we can also free the `pArray` pointer as it's only used when constructing a `Map` (Line 29, while iterating over to the `IKeyValuePair`'s `key` and `value` getters). After that, we don't need `pArray` at all. Therefore, we can safely free it in a `finally` block.

Because of that, I think it's safe to free the `retValuePtr` since we don't return the `IMapView` object.

**Comment by timsneath** [comment]
Great! I think we're good here then. Thanks!
