### ISSUE TITLE
RFCOMM Bluetooth Support

### ISSUE THREAD

**Issue by ghost** [halildurmus/win32#639]
Please add Bluetooth Classic support to the Dart win32 library.  Enhance the bluetooth.dart example using SOCKADDR_BTH for the connection, send and recv.  Also include support for ws2bth.h and Ws2_32.lib.

**Comment by timsneath** [comment]
I've added all the remaining Bluetooth APIs I could find. Please take a look and let me know if you see something missing.
https://github.com/timsneath/win32/pull/640

Winsock 2 is a separate import, because of its usage of common function names. To import Winsock, add the following import statement:

 ```dart
import 'package:win32/win32.dart';
import 'package:win32/winsock2.dart' as winsock2;
```

Now you can call, for instance, `winsock2.connect()` or `winsock2.send()`.

**Comment by ghost** [comment]
Thanks!  Looking forward to using RFCOMM and SDP.
