### ISSUE TITLE
ShowCursor should use BOOL bShow and pass it in as a parameter.

### ISSUE THREAD

**Issue by user1121114685** [halildurmus/win32#831]
int ShowCursor(int bShow) => _ShowCursor(bShow);

final _ShowCursor = _user32.lookupFunction<Int32 Function(Int32 bShow),
    int Function(int bShow)>('ShowCursor');`

---
This method of hiding the mouse also does not work. It may be because this parameter is wrong. You should use BOOL bShow and pass it in as a parameter.
---
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\WinUser.h
---

int
WINAPI
ShowCursor(
    _In_ BOOL bShow);

_Originally posted by @user1121114685 in https://github.com/dart-windows/win32/issues/313#issuecomment-2005780078_

**Comment by halildurmus** [comment]
There is no issue with the parameter.

`BOOL` is defined as a struct with a single `int` field in the [metadata](https://github.com/microsoft/win32metadata):

![Screenshot 2024-03-19 121316](https://github.com/dart-windows/win32/assets/45524029/4e807361-5ce4-4286-9d8c-d4e2cc552790)

Since this struct is marked with a [NativeTypeDef](https://github.com/microsoft/win32metadata/blob/7344bf7c5aba2293b2756b0a76c67af79cc837ba/docs/projections.md?plain=1#L74) attribute, we simplify it by projecting it as `int` for ease of use.

**Comment by user1121114685** [comment]
Hi Developer, can you check why ShowCursor is not working? I passed `ShowCursor(0)` in dart; the mouse is not hidden!
