### ISSUE TITLE
Error: Type 'UnmodifiableUint8ListView' not found.

### ISSUE THREAD

**Issue by drxddy** [halildurmus/win32#887]
Using flutter latest version, giving this Error: Type 'UnmodifiableUint8ListView' not found.

### Expected behavior

it should compile and run without any errors

### Environment

macOS  14.6.1  23G93

**Comment by halildurmus** [comment]
The `UnmodifiableUint8ListView` class was removed in Dart `v3.5`, and the `package:win32` has not used it since [v5.5.1](https://pub.dev/packages/win32/versions/5.5.1/changelog). One of the packages you depend on is likely using an older version of `package:win32` (pre-5.5.1), which is causing the error you're encountering.

There are a few ways to fix this error. I suggest trying one of the workarounds described in the following issue:
https://github.com/jonataslaw/get_cli/issues/263

**Comment by drxddy** [comment]
thanks so much @halildurmus
